### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ImJunSang** [ImJunSang/interface-dependency#1]
- [x] PC 접속 차단
- [x] user_id 검증
- [x] header 수정
- [x] 작업 지시문 추가, 삼성 인터넷 위로 가기 버튼 경고 및 비활성 안내
- [x] 작업 완료 시 재작업 불가능
